"""Generate the embeddable adaptive-EQ target curves header from the empirical
reference spectra in weights/auto_eq_refs/*.npz.

The .npz curves come from scripts/extract_class_targets.py, which stores the
long-term log-mel power spectrum (median over a corpus). Two conventions must be
reconciled before the C++ AdaptiveEqController can use them as targets:

  1. NORMALIZATION. extract_class_targets uses `mel_power = power @ fb.T` — a SUM
     over the triangular mel filters with NO area normalization. For a flat
     (white) input that rises toward HF (wider bands sum more bins). The runtime
     RunningMelSpectrum divides by the per-band weight sum (MEAN / power density),
     so a flat input reads flat. We convert sum→density by subtracting
     10*log10(Σ filter weights) per band, reconstructing the exact same
     triangular filterbank from the stored (n_fft, n_mels, sample_rate).

  2. LEVEL. Only the SHAPE matters (the controller zero-means the target−measured
     difference and applies an energy makeup), so we re-zero-mean after the
     density correction. The absolute offset is irrelevant.

Output: native/clap/src/adaptive_eq_targets.hpp — per-class (mel_hz, density_db)
arrays + a log-frequency-interpolating lookup. Regenerate whenever the refs
change:  python scripts/gen_target_curves.py
"""

from __future__ import annotations

import glob
import math
import os
from pathlib import Path

import numpy as np

REFS_DIR = Path("weights/auto_eq_refs")
OUT_HDR = Path("native/clap/src/adaptive_eq_targets.hpp")
# full_mix is the master-bus default; keep a stable, documented order.
CLASS_ORDER = ["full_mix", "bass", "drums", "vocals", "other"]


def _filter_weight_sums(sample_rate: int, n_fft: int, n_mels: int) -> np.ndarray:
    """Reconstruct extract_class_targets' triangular mel filterbank and return
    Σ weights per band — the sum→density correction divisor."""
    eps = 1e-8
    n_freqs = n_fft // 2 + 1
    mel_min = 2595.0 * math.log10(1.0 + 20.0 / 700.0)
    mel_max = 2595.0 * math.log10(1.0 + (sample_rate / 2) / 700.0)
    mel_pts = np.linspace(mel_min, mel_max, n_mels + 2)
    hz_pts = 700.0 * (10 ** (mel_pts / 2595.0) - 1.0)
    bins = np.clip(hz_pts * (n_fft / sample_rate), 0, n_freqs - 1)
    idx = np.arange(n_freqs, dtype=np.float64)
    wsum = np.zeros(n_mels, dtype=np.float64)
    for m in range(n_mels):
        left, center, right = bins[m], bins[m + 1], bins[m + 2]
        up = (idx - left) / (center - left + eps)
        dn = (right - idx) / (right - center + eps)
        fb = np.clip(np.minimum(up, dn), 0.0, None)
        wsum[m] = max(fb.sum(), eps)
    return wsum


def _density_curve(npz_path: Path) -> tuple[np.ndarray, np.ndarray, str, int]:
    d = np.load(npz_path)
    name = str(d["class_name"])
    sr = int(d["sample_rate"]); n_fft = int(d["n_fft"]); n_mels = int(d["n_mels"])
    hz = d["mel_hz"].astype(np.float64)
    db_sum = d["target_log_power_db"].astype(np.float64)
    wsum = _filter_weight_sums(sr, n_fft, n_mels)
    db_density = db_sum - 10.0 * np.log10(wsum)   # sum → power density
    db_density -= db_density.mean()               # shape only (re-zero-mean)
    return hz, db_density.astype(np.float32), name, int(d["n_tracks"])


def _fmt_arr(vals: np.ndarray, per_line: int = 8) -> str:
    out, line = [], []
    for i, v in enumerate(vals):
        line.append(f"{float(v):.4f}f")
        if (i + 1) % per_line == 0:
            out.append("    " + ", ".join(line) + ","); line = []
    if line:
        out.append("    " + ", ".join(line) + ",")
    return "\n".join(out)


def main() -> None:
    files = {Path(p).stem: Path(p) for p in glob.glob(str(REFS_DIR / "*.npz"))}
    classes = [c for c in CLASS_ORDER if c in files] + \
              [c for c in sorted(files) if c not in CLASS_ORDER]
    if not classes:
        raise SystemExit(f"no .npz under {REFS_DIR}")

    body, entries = [], []
    for cls in classes:
        hz, db, name, ntr = _density_curve(files[cls])
        body.append(f"// {name}: {len(hz)} mel bands, {ntr} tracks, density-normalized, zero-mean dB")
        body.append(f"static const float kHz_{cls}[] = {{\n{_fmt_arr(hz)}\n}};")
        body.append(f"static const float kDb_{cls}[] = {{\n{_fmt_arr(db)}\n}};")
        body.append("")
        entries.append(f'    {{ "{name}", {len(hz)}, kHz_{cls}, kDb_{cls} }},')

    hdr = f"""// GENERATED by scripts/gen_target_curves.py — DO NOT EDIT BY HAND.
// Empirical adaptive-EQ tonal-balance target curves, from
// weights/auto_eq_refs/*.npz (corpus medians), converted from the extract's
// sum-mel convention to the runtime's density (mean) convention and zero-meaned
// (shape only). Regenerate: python scripts/gen_target_curves.py
#pragma once
#include <cmath>
#include <cstring>

namespace nablafx {{ namespace adaptive_eq_detail {{

struct TargetCurve {{ const char* name; int n; const float* hz; const float* db; }};

{chr(10).join(body)}
static const TargetCurve kTargetCurves[] = {{
{chr(10).join(entries)}
}};
static const int kNumTargetCurves = {len(classes)};

// Index of a named curve, or -1. (Default lookups use full_mix at index 0.)
inline int target_curve_index(const char* name) {{
    for (int i = 0; i < kNumTargetCurves; ++i)
        if (std::strcmp(kTargetCurves[i].name, name) == 0) return i;
    return -1;
}}

// Target dB at frequency f for curve `idx`, linear-interpolated in log-frequency
// and clamped to the curve's endpoints. Out-of-range idx falls back to curve 0.
inline double target_curve_db(double f, int idx) {{
    if (idx < 0 || idx >= kNumTargetCurves) idx = 0;
    const TargetCurve& c = kTargetCurves[idx];
    const double lf = std::log2(f < 1.0 ? 1.0 : f);
    if (lf <= std::log2((double)c.hz[0]))     return c.db[0];
    if (lf >= std::log2((double)c.hz[c.n-1])) return c.db[c.n-1];
    for (int i = 1; i < c.n; ++i) {{
        const double l1 = std::log2((double)c.hz[i]);
        if (lf <= l1) {{
            const double l0 = std::log2((double)c.hz[i-1]);
            const double t = (lf - l0) / (l1 - l0);
            return (1.0 - t) * c.db[i-1] + t * c.db[i];
        }}
    }}
    return c.db[c.n-1];
}}

}} }}  // namespace nablafx::adaptive_eq_detail
"""
    OUT_HDR.write_text(hdr)
    print(f"wrote {OUT_HDR}  ({len(classes)} curves: {', '.join(classes)})")
    # sanity print: full_mix tilt at octave centers
    hz, db, _, _ = _density_curve(files[classes[0]])
    print(f"\n{classes[0]} density target (zero-mean dB):")
    for tgt in [60, 125, 250, 500, 1000, 2000, 4000, 8000, 16000]:
        i = int(np.argmin(np.abs(hz - tgt)))
        print(f"   {hz[i]:6.0f} Hz : {db[i]:+6.1f} dB")


if __name__ == "__main__":
    main()
