// GENERATED by scripts/fit_amek_eq.py — do not edit by hand.
// Source dataset: eqds run amek9099-v1-55884e47 (qa.tf_mag_db + plugin read-back knobs).
// Shape-law coefficients for the AMEK 9099-style EQ voicing (amek_eq.hpp).
//
// Validation vs measured curves (per-example RMS over 20 Hz-20 kHz):
// train n=7500  AMEK model rms dB: median 0.242 / p90 0.593 / max 2.750
//                 AMEK model max|err| dB: median 0.693 / p90 1.566 / max 8.177
//                 panel labels as knobs rms: median 1.637 / p90 5.441 / max 10.067
//                 SSL voicing, same knobs rms: median 2.732 / p90 5.061 / max 14.347
// eval  n=500  AMEK model rms dB: median 0.249 / p90 0.592 / max 2.136
//                 AMEK model max|err| dB: median 0.697 / p90 1.530 / max 4.134
//                 panel labels as knobs rms: median 1.629 / p90 5.005 / max 9.540
//                 SSL voicing, same knobs rms: median 2.810 / p90 4.783 / max 9.255

#pragma once

namespace nablafx::amek_fit {

inline constexpr double kLF_FREF = 100.0;
inline constexpr double kLMF_FREF = 300.0;
inline constexpr double kHMF_FREF = 2000.0;
inline constexpr double kHF_FREF = 6000.0;
inline constexpr double kHPF_FREF = 100.0;
inline constexpr double kLPF_FREF = 8000.0;

inline constexpr double kLMF_URANGE[2] = {-2.6548159445, 1.66024386248};
inline constexpr double kLMF_LOGK = -1.14521478057;
inline constexpr double kLMF_BETA[4] = {0.0470464146894, 0.0803786622441, -0.00385413287039, 0.000339781374859};

inline constexpr double kHMF_URANGE[2] = {-2.04448375912, 2.31568216793};
inline constexpr double kHMF_LOGK = -1.17887472578;
inline constexpr double kHMF_BETA[4] = {-0.00581727793788, 0.105010300368, 0.00145627755849, 0.001543805484};

inline constexpr double kLF_BELL_URANGE[2] = {-1.61447676236, 1.55612665231};
inline constexpr double kLF_BELL_BETA[6] = {-0.572392209949, -0.00535170684374, 0.368720988666, 0.0189563528022, -0.00469569443643, -0.0237252380875};
inline constexpr double kLF_SHELF_URANGE[2] = {-0.0232767097231, 2.15150076225};
inline constexpr double kLF_SHELF_BZ[6] = {-0.0706067453203, 0.0781012380291, -0.0642562132852, 0.0499043444373, -0.164461344303, -0.280127738813};
inline constexpr double kLF_SHELF_BD[3] = {-0.137218839167, -0.126070146713, 0.621081214499};

inline constexpr double kHF_BELL_URANGE[2] = {-1.43773645855, 2.27035052617};
inline constexpr double kHF_BELL_BETA[6] = {-0.949841371397, -0.00242782173233, 0.358458687951, 0.0620851124148, 0.0232091734488, 0.00728556293718};
inline constexpr double kHF_SHELF_URANGE[2] = {-3.03589263153, -0.39409123603};
inline constexpr double kHF_SHELF_BZ[6] = {-1.12662951159, 0.522898033115, -0.073475331834, -0.832388701478, -0.212058191175, 0.276950404357};
inline constexpr double kHF_SHELF_BD[3] = {-1.10067501738, -0.0480286927518, -0.58537972926};

inline constexpr double kHPF_URANGE[2] = {-2.47676592304, 3.34697506614};
inline constexpr double kHPF_B_FC2[3] = {0.0728276315922, 0.000327083785823, -0.00581727817312};
inline constexpr double kHPF_B_Q[3] = {0.112637790877, -0.00819582373221, -0.00373846111363};
inline constexpr double kHPF_B_K[3] = {-0.0187354714632, -0.0052280113584, 0.00742651063975};

inline constexpr double kLPF_URANGE[2] = {-2.40325854448, 1.25556346561};
inline constexpr double kLPF_B_FA[3] = {1.07524547632, -0.442767964803, -0.116214731471};
inline constexpr double kLPF_B_QA[3] = {-1.29485083049, 0.366155935904, 0.0842069927246};
inline constexpr double kLPF_B_K[3] = {-1.19426455786, 0.460863578567, 0.129365626607};
inline constexpr double kLPF_B_QB[3] = {0.208244202987, 0.00153964632682, 0.00594304973134};

}  // namespace nablafx::amek_fit
