// AMEK 9099-style channel-EQ voicing — section designs for SslChannelEq.
//
//   HPF 3rd order (2nd-order HP + 1st-order HP), bilinear
//   LF  shelf: general 2nd-order section (own zero/pole Q)   | bell: proportional-Q peak
//   LMF RBJ peaking (bilinear), constant Q on the console's broad Q scale
//   HMF RBJ peaking (bilinear), constant Q on the console's broad Q scale
//   HF  shelf: general 2nd-order section                     | bell: proportional-Q peak
//   LPF two 2nd-order LP sections (fits the console's ~18 dB/oct + corner bump)
//
// The shape laws (Q vs gain/frequency, filter section spacing) are GENERATED by
// scripts/fit_amek_eq.py from an eqds transfer-function dataset of the console
// (amek_eq_fit.hpp); this file only evaluates them. It mirrors the Python
// Model/section functions exactly — tests/test_amek_eq.cpp pins it to the
// script's golden vectors and to held-out measured curves.
//
// Knob semantics (shared with the Classic voicing so an EQ-type A/B keeps
// bands in place): freq = bell centre / shelf midpoint (geometric centre of the
// pole and zero pairs) / filter -3 dB point; gain = peak / asymptotic plateau
// gain in dB; LMF/HMF Q is the console's scale (Q_rbj ≈ 0.31·Q_knob). Knob
// values outside the measured console range extrapolate: frequencies scale
// exactly, shape laws clamp to the measured range.
//
// "Matched" sections are decramped: impulse-invariant poles + a numerator
// magnitude-matched to the analog prototype (exact at DC and Nyquist, closed-
// form least squares in between). The measured HF bands keep their gain up to
// Nyquist, unlike an RBJ bilinear design; the measured HMF bell does cramp to
// 0 dB at Nyquist, so the mid bells stay RBJ. Pure DSP, header-only.

#pragma once

#include <algorithm>
#include <cmath>

#include "amek_eq_fit.hpp"

namespace nablafx::amek {

struct Coeffs { double b0 = 1, b1 = 0, b2 = 0, a1 = 0, a2 = 0; };   // a0-normalized

constexpr double kPi = 3.14159265358979323846;
constexpr double kMaxPoleFrac = 0.45;   // matched-design pole clamp (x fs)
constexpr int    kMatchPoints = 16;     // numerator least-squares grid size

// --- bilinear sections (RBJ cookbook; identical to ssl_design types 0/3) ------

inline Coeffs rbj_peak(double g_db, double f0, double q, double fs) {
    f0 = std::min(std::max(f0, 1.0), 0.49 * fs);
    q = std::max(q, 1e-3);
    const double A = std::pow(10.0, g_db / 40.0), w0 = 2.0 * kPi * f0 / fs;
    const double cw = std::cos(w0), al = std::sin(w0) / (2.0 * q), a0 = 1.0 + al / A;
    return {(1.0 + al * A) / a0, -2.0 * cw / a0, (1.0 - al * A) / a0, -2.0 * cw / a0, (1.0 - al / A) / a0};
}

inline Coeffs bilinear_hp2(double fc, double q, double fs) {
    fc = std::min(std::max(fc, 1.0), 0.49 * fs);
    q = std::max(q, 1e-3);
    const double w0 = 2.0 * kPi * fc / fs, cw = std::cos(w0), al = std::sin(w0) / (2.0 * q);
    const double a0 = 1.0 + al;
    return {(1.0 + cw) / 2.0 / a0, -(1.0 + cw) / a0, (1.0 + cw) / 2.0 / a0, -2.0 * cw / a0, (1.0 - al) / a0};
}

inline Coeffs bilinear_hp1(double fc, double fs) {
    fc = std::min(std::max(fc, 1.0), 0.49 * fs);
    const double K = std::tan(kPi * fc / fs), n = 1.0 / (1.0 + K);
    return {n, -n, 0.0, (K - 1.0) / (K + 1.0), 0.0};
}

// --- analog prototypes: H(s) = (n2 s^2 + n1 s + n0) / (s^2 + d1 s + d0), rad/s ---

struct Proto { double n2, n1, n0, d1, d0; };

inline double analog_mag2(const Proto& p, double w) {
    const double nr = p.n0 - p.n2 * w * w, ni = p.n1 * w;
    const double dr = p.d0 - w * w,        di = p.d1 * w;
    return (nr * nr + ni * ni) / std::max(dr * dr + di * di, 1e-300);
}

inline Proto proto_peak(double g_db, double f0, double q) {
    const double A = std::pow(10.0, g_db / 40.0), w = 2.0 * kPi * f0;
    return {1.0, A * w / q, w * w, w / (A * q), w * w};
}

// General 2nd-order shelf. lf: DC gain g, HF gain 0 dB; hf: the reverse.
// fz*fp = fg^2, the pair ratio sets the plateau.
inline Proto proto_shelf(bool lf, double g_db, double fg, double qz, double qp) {
    const double r = std::pow(10.0, g_db / 80.0);
    const double fz = lf ? fg * r : fg / r, fp = lf ? fg / r : fg * r;
    const double k = lf ? 1.0 : (fp / fz) * (fp / fz);
    const double wz = 2.0 * kPi * fz, wp = 2.0 * kPi * fp;
    return {k, k * wz / qz, k * wz * wz, wp / qp, wp * wp};
}

inline Proto proto_lp(double fc, double q) {
    const double w = 2.0 * kPi * fc;
    return {0.0, 0.0, w * w, w / q, w * w};
}

// --- decramped (matched) design -------------------------------------------------

inline Coeffs matched_core(const Proto& p, double fs) {
    double wn = std::sqrt(std::max(p.d0, 1e-30));
    const double zeta = p.d1 / (2.0 * wn);
    wn = std::min(wn, 2.0 * kPi * kMaxPoleFrac * fs);   // keep poles below Nyquist
    const double T = 1.0 / fs;
    double a1, a2;
    if (zeta < 1.0) {
        const double e = std::exp(-zeta * wn * T);
        a1 = -2.0 * e * std::cos(wn * T * std::sqrt(1.0 - zeta * zeta));
        a2 = e * e;
    } else {   // two real poles; slow root written cancellation-free
        const double sq = std::sqrt(zeta * zeta - 1.0);
        const double r_fast = std::exp(-wn * T * (zeta + sq));
        const double r_slow = std::exp(-wn * T / (zeta + sq));
        a1 = -(r_fast + r_slow);
        a2 = r_fast * r_slow;
    }
    // |P(e^jw)|^2 = B0*phi0 + B1*phi1 + B2*phi2, phi1 = sin^2(w/2), phi0 = 1-phi1,
    // phi2 = 4*phi0*phi1. Pin B0/B1 to the analog DC/Nyquist gains; fit B2.
    const double A0 = (1 + a1 + a2) * (1 + a1 + a2), A1 = (1 - a1 + a2) * (1 - a1 + a2), A2 = -4.0 * a2;
    const double B0 = analog_mag2(p, 0.0) * A0;
    const double B1 = analog_mag2(p, kPi * fs) * A1;
    const double wz = (p.n2 > 0.0 && p.n0 > 0.0) ? std::sqrt(p.n0 / p.n2) : wn;
    const double f_lo = std::max(std::min(wn, wz) / (2.0 * kPi) / 4.0, 5.0);
    const double f_hi = 0.499 * fs;
    double num = 0.0, den = 0.0;
    for (int k = 0; k < kMatchPoints; ++k) {
        const double f = f_lo * std::pow(f_hi / f_lo, (double)k / (kMatchPoints - 1));
        const double w = 2.0 * kPi * f / fs, s = std::sin(w / 2.0);
        const double p1 = s * s, p0 = 1.0 - p1, p2 = 4.0 * p0 * p1;
        const double tgt = analog_mag2(p, 2.0 * kPi * f) * (A0 * p0 + A1 * p1 + A2 * p2);
        const double wt = 1.0 / std::max(tgt * tgt, 1e-300);
        num += wt * p2 * (tgt - B0 * p0 - B1 * p1);
        den += wt * p2 * p2;
    }
    const double B2 = den > 0.0 ? num / den : 0.0;
    const double sB0 = std::sqrt(std::max(B0, 0.0)), sB1 = std::sqrt(std::max(B1, 0.0));
    const double W = 0.5 * (sB0 + sB1), disc = std::sqrt(std::max(W * W + B2, 0.0));
    return {0.5 * (W + disc), 0.5 * (sB0 - sB1), 0.5 * (W - disc), a1, a2};
}

// Always let impulse invariance place the lower / sharper pole pair: when H's
// zeros are the lower pair (a cut peak, a rising HF shelf, a falling LF shelf)
// design 1/H and invert — exact, since every section here is minimum phase.
inline Coeffs matched(const Proto& p, double fs) {
    if (p.n2 > 0.0 && p.n0 > 0.0) {
        const double wz = std::sqrt(p.n0 / p.n2), zz = p.n1 / (2.0 * p.n2 * wz);
        const double wp = std::sqrt(p.d0),        zp = p.d1 / (2.0 * wp);
        if (wz < wp * (1.0 - 1e-9) || (std::fabs(wz - wp) <= 1e-9 * wp && zz < zp)) {
            const Coeffs c = matched_core({1.0 / p.n2, p.d1 / p.n2, p.d0 / p.n2,
                                           p.n1 / p.n2, p.n0 / p.n2}, fs);
            return {1.0 / c.b0, c.a1 / c.b0, c.a2 / c.b0, c.b1 / c.b0, c.b2 / c.b0};
        }
    }
    return matched_core(p, fs);
}

// --- shape laws -------------------------------------------------------------------

namespace detail {
inline double clamp_u(double f, double fref, const double (&ur)[2]) {
    return std::min(std::max(std::log2(std::max(f, 1e-3) / fref), ur[0]), ur[1]);
}
inline double clamp_v(double g) { return std::min(std::max(g / 18.0, -1.0), 1.0); }
template <size_t N>
inline double dot(const double (&c)[N], const double (&x)[N]) {
    double s = 0.0;
    for (size_t i = 0; i < N; ++i) s += c[i] * x[i];
    return s;
}
}  // namespace detail

// LMF / HMF bell. q is the knob (console scale).
inline Coeffs mid_bell(bool hmf, double g, double f, double q, double fs) {
    using namespace amek_fit;
    const double u = detail::clamp_u(f, hmf ? kHMF_FREF : kLMF_FREF, hmf ? kHMF_URANGE : kLMF_URANGE);
    const double v = detail::clamp_v(g);
    const double x[4] = {v, v * v, u, u * u};
    const double lq = std::log(std::max(q, 1e-3)) + (hmf ? kHMF_LOGK : kLMF_LOGK) +
                      detail::dot(hmf ? kHMF_BETA : kLMF_BETA, x);
    return rbj_peak(g, f, std::exp(lq), fs);
}

// LF / HF proportional-Q bell.
inline Coeffs edge_bell(bool hf, double g, double f, double fs) {
    using namespace amek_fit;
    const double u = detail::clamp_u(f, hf ? kHF_FREF : kLF_FREF, hf ? kHF_BELL_URANGE : kLF_BELL_URANGE);
    const double v = detail::clamp_v(g);
    const double x[6] = {1.0, v, v * v, std::fabs(v), u, u * u};
    const double q = std::exp(detail::dot(hf ? kHF_BELL_BETA : kLF_BELL_BETA, x));
    return matched(proto_peak(g, f, q), fs);
}

// LF / HF shelf. Pole Q = zero Q · exp(v·…), so a 0 dB shelf is exactly flat.
inline Coeffs shelf(bool hf, double g, double f, double fs) {
    using namespace amek_fit;
    const double u = detail::clamp_u(f, hf ? kHF_FREF : kLF_FREF, hf ? kHF_SHELF_URANGE : kLF_SHELF_URANGE);
    const double v = detail::clamp_v(g);
    const double xz[6] = {1.0, v, v * v, u, u * u, u * v};
    const double xd[3] = {v, v * v, u * v};
    const double qz = std::exp(detail::dot(hf ? kHF_SHELF_BZ : kLF_SHELF_BZ, xz));
    const double qp = qz * std::exp(detail::dot(hf ? kHF_SHELF_BD : kLF_SHELF_BD, xd));
    return matched(proto_shelf(!hf, g, f, qz, qp), fs);
}

// 18 dB/oct high-pass; f3 is the -3 dB knob.
inline void hpf(double f3, double fs, Coeffs out[2]) {
    using namespace amek_fit;
    const double u = detail::clamp_u(f3, kHPF_FREF, kHPF_URANGE);
    const double x[3] = {1.0, u, u * u};
    const double fc2 = f3 * std::exp(detail::dot(kHPF_B_FC2, x));
    out[0] = bilinear_hp2(fc2, std::exp(detail::dot(kHPF_B_Q, x)), fs);
    out[1] = bilinear_hp1(fc2 * std::exp(detail::dot(kHPF_B_K, x)), fs);
}

// ~18 dB/oct low-pass with the console's small pre-corner bump (decramped);
// f3 is the -3 dB knob.
inline void lpf(double f3, double fs, Coeffs out[2]) {
    using namespace amek_fit;
    const double u = detail::clamp_u(f3, kLPF_FREF, kLPF_URANGE);
    const double x[3] = {1.0, u, u * u};
    const double fa = f3 * std::exp(detail::dot(kLPF_B_FA, x));
    const double fb = fa * std::exp(detail::dot(kLPF_B_K, x));
    out[0] = matched(proto_lp(fa, std::exp(detail::dot(kLPF_B_QA, x))), fs);
    out[1] = matched(proto_lp(fb, std::exp(detail::dot(kLPF_B_QB, x))), fs);
}

}  // namespace nablafx::amek
